from topcv_scraper.topcv_scraper.filters import IndustryFilter as TopcvIndustryFilter
from linkedin_scraper.linkedin_scraper.filters import IndustryFilter as LinkedinIndustryFilters
from enum import Enum

class IndustryMapping(Enum):
    Agency_Design_Development = (TopcvIndustryFilter.Agency_Design_Development, None)
    Agency_Marketing_Advertising = (TopcvIndustryFilter.Agency_Marketing_Advertising, None)
    Retail_Consumer_Goods_FMCG = (TopcvIndustryFilter.Retail_Consumer_Goods_FMCG, None)
    Insurance = (TopcvIndustryFilter.Insurance, LinkedinIndustryFilters.FINANCIAL_SERVICES)
    Real_Estate = (TopcvIndustryFilter.Real_Estate, None)
    Securities = (TopcvIndustryFilter.Securities, None)
    Mechanical = (TopcvIndustryFilter.Mechanical, None)
    Government_Agency = (TopcvIndustryFilter.Government_Agency, None)
    Tourism = (TopcvIndustryFilter.Tourism, None)
    Pharmaceuticals_Healthcare_Biotechnology = (TopcvIndustryFilter.Pharmaceuticals_Healthcare_Biotechnology, None)
    Electronics_Refrigeration = (TopcvIndustryFilter.Electronics_Refrigeration, LinkedinIndustryFilters.TECHNOLOGY_INTERNET)
    Entertainment = (TopcvIndustryFilter.Entertainment, None)
    Education_Training = (TopcvIndustryFilter.Education_Training, None)
    Printing_Publishing = (TopcvIndustryFilter.Printing_Publishing, None)
    Internet_Online = (TopcvIndustryFilter.Internet_Online, LinkedinIndustryFilters.TECHNOLOGY_INTERNET)
    IT_Hardware = (TopcvIndustryFilter.IT_Hardware, None)
    IT_Software = (TopcvIndustryFilter.IT_Software, LinkedinIndustryFilters.TECHNOLOGY_INTERNET)
    Accounting_Auditing = (TopcvIndustryFilter.Accounting_Auditing, LinkedinIndustryFilters.FINANCIAL_SERVICES)
    Other = (TopcvIndustryFilter.Other, None)
    Logistics_Transportation = (TopcvIndustryFilter.Logistics_Transportation, None)
    Law = (TopcvIndustryFilter.Law, LinkedinIndustryFilters.LEGAL_SERVICES)
    Marketing_Communications_Advertising = (TopcvIndustryFilter.Marketing_Communications_Advertising, None)
    Environment = (TopcvIndustryFilter.Environment, LinkedinIndustryFilters.ENVIRONMENTAL_SERVICES)
    Energy = (TopcvIndustryFilter.Energy, None)
    Banking = (TopcvIndustryFilter.Banking, LinkedinIndustryFilters.FINANCIAL_SERVICES)
    Restaurant_Hotel = (TopcvIndustryFilter.Restaurant_Hotel, None)
    Human_Resources = (TopcvIndustryFilter.Human_Resources, LinkedinIndustryFilters.STAFFING_RECRUITING)
    Agriculture_Forestry_Fisheries = (TopcvIndustryFilter.Agriculture_Forestry_Fisheries, None)
    Manufacturing = (TopcvIndustryFilter.Manufacturing, None)
    Finance = (TopcvIndustryFilter.Finance, LinkedinIndustryFilters.FINANCIAL_SERVICES)
    Design_Architecture = (TopcvIndustryFilter.Design_Architecture, None)
    Fashion = (TopcvIndustryFilter.Fashion, None)
    Ecommerce = (TopcvIndustryFilter.Ecommerce, None)
    Non_Profit_Organization = (TopcvIndustryFilter.Non_Profit_Organization, None)
    Automation = (TopcvIndustryFilter.Automation, None)
    Consultancy = (TopcvIndustryFilter.Consultancy, None)
    Telecommunications = (TopcvIndustryFilter.Telecommunications, LinkedinIndustryFilters.TECHNOLOGY_INTERNET)
    Construction = (TopcvIndustryFilter.Construction, None)
    Import_Export = (TopcvIndustryFilter.Import_Export, None)