JOBS_SEARCH_URL = 'https://www.topcv.vn/tim-viec-lam-moi-nhat'
cities = {
    "1": "Ha Noi",
    "2": "Ho Chi Minh",
    "3": "Binh Duong",
    "4": "Bac Ninh",
    "5": "Dong Nai",
    "6": "Hung Yen",
    "7": "Hai Duong",
    "8": "Da Nang",
    "9": "Hai Phong",
    "10": "An Giang",
    "11": "Ba Ria-Vung Tau",
    "12": "Bac Giang",
    "13": "Bac Kan",
    "14": "Bac Lieu",
    "15": "Ben Tre",
    "16": "Binh Dinh",
    "17": "Binh Phuoc",
    "18": "Binh Thuan",
    "19": "Ca Mau",
    "20": "Can Tho",
    "21": "Cao Bang",
    "22": "Cuu Long",
    "23": "Dak Lak",
    "24": "Dak Nong",
    "25": "Dien Bien",
    "26": "Dong Thap",
    "27": "Gia Lai",
    "28": "Ha Giang",
    "29": "Ha Nam",
    "30": "Ha Tinh",
    "31": "Hau Giang",
    "32": "Hoa Binh",
    "33": "Khanh Hoa",
    "34": "Kien Giang",
    "35": "Kon Tum",
    "36": "Lai Chau",
    "37": "Lam Dong",
    "38": "Lang Son",
    "39": "Lao Cai",
    "40": "Long An",
    "41": "Mien Bac",
    "42": "Mien Nam",
    "43": "Mien Trung",
    "44": "Nam Dinh",
    "45": "Nghe An",
    "46": "Ninh Binh",
    "47": "Ninh Thuan",
    "48": "Phu Tho",
    "49": "Phu Yen",
    "50": "Quang Binh",
    "51": "Quang Nam",
    "52": "Quang Ngai",
    "53": "Quang Ninh",
    "54": "Quang Tri",
    "55": "Soc Trang",
    "56": "Son La",
    "57": "Tay Ninh",
    "58": "Thai Binh",
    "59": "Thai Nguyen",
    "60": "Thanh Hoa",
    "61": "Thua Thien Hue",
    "62": "Tien Giang",
    "63": "Toan Quoc",
    "64": "Tra Vinh",
    "65": "Tuyen Quang",
    "66": "Vinh Long",
    "67": "Vinh Phuc",
    "68": "Yen Bai",
    "100": "Nuoc Ngoai"
}


cities_reverse = {v: k for k, v in cities.items()}

types = {
    "1": "FULL_TIME",
    "3": "PART_TIME",
    "5": "INTERNSHIP",
}

types_reverse = {v: k for k, v in types.items()}

industry = {
    None: "Tất cả lĩnh vực",
    "33": "Agency (Design/Development)",
    "34": "Agency (Marketing/Advertising)",
    "11": "Bán lẻ - Hàng tiêu dùng - FMCG",
    "4": "Bảo hiểm",
    "20": "Bảo trì / Sửa chữa",
    "5": "Bất động sản",
    "13": "Chứng khoán",
    "23": "Cơ khí",
    "30": "Cơ quan nhà nước",
    "31": "Du lịch",
    "6": "Dược phẩm / Y tế / Công nghệ sinh học",
    "21": "Điện tử / Điện lạnh",
    "36": "Giải trí",
    "26": "Giáo dục / Đào tạo",
    "10": "In ấn / Xuất bản",
    "7": "Internet / Online",
    "37": "IT - Phần cứng",
    "1": "IT - Phần mềm",
    "2": "Kế toán / Kiểm toán",
    "10000": "Khác",
    "28": "Logistics - Vận tải",
    "3": "Luật",
    "8": "Marketing / Truyền thông / Quảng cáo",
    "18": "Môi trường",
    "35": "Năng lượng",
    "15": "Ngân hàng",
    "9": "Nhà hàng / Khách sạn",
    "16": "Nhân sự",
    "38": "Nông Lâm Ngư nghiệp",
    "12": "Sản xuất",
    "39": "Tài chính",
    "17": "Thiết kế / kiến trúc",
    "22": "Thời trang",
    "27": "Thương mại điện tử",
    "29": "Tổ chức phi lợi nhuận",
    "32": "Tự động hóa",
    "24": "Tư vấn",
    "25": "Viễn thông",
    "14": "Xây dựng",
    "19": "Xuất nhập khẩu"
}

industry_reverse = {v: k for k, v in industry.items()}